security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: true

    providers:
        db_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            lazy: true
            guard:
                authenticators:
                    - App\Security\ApiKeyAuthenticator
            logout:
                path: app_logout

    access_control:
        - { path: ^/api/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/, roles: IS_AUTHENTICATED_FULLY }