security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: true
    providers:
        db_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: db_user_provider
            guard:
                authenticators:
                    - App\Security\ApiKeyAuthenticator
    access_control:
        - { path: ^/api/v1/login, roles: PUBLIC_ACCESS }
        - { path: '^/api/v1/', roles: ROLE_USER }